//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabVet.Models
{
    using System;
    using System.Collections.Generic;

    public enum TipoTelefone
    {
        Residencial = 0,
        Celular
    }
    
    public partial class Telefone
    {
        public Telefone()
        {
            
        }
    
        public int ID { get; set; }
        public string NumeroTelefone { get; set; }
        public TipoTelefone TipoTelefone { get; set; }       
    
        public virtual Proprietario Proprietario { get; set; }        
    }
}
